---
- hosts: all
  roles:
    - common.common
    - post.discordsh
    - util.netdata
    - lb.nginx
    - lb.alp
    - lb.restart
    - prepare.clear_mysql_log
    - prepare.clear_nginx_log
    - db.mysql
    - db.restart
    - db.pt_query_digest
    - lang.rust
    - lang.golang
